# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# This Vagrant environment requires Vagrant 1.6.0 or higher.
Vagrant.require_version ">= 1.6.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "192.168.33.32"

  # Configure port forwarding
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "../project","/var/www/",owner:"vagrant",group:"www-data",mount_options:["dmode=775,fmode=664"]

  # rename box
  config.vm.define "laravel5Semantic" do |laravel5Semantic| end

  # Provision the VirtualBoxe with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.raw_arguments = ['-v']
  end

  # Configure VM settings for server running in VirtualBox
  config.vm.provider "virtualbox" do |vb|
    # this is the name in the VirtualBox Manager UI
    vb.name = "laravel5Semantic"
    # set the system memory for the virtual machine
    vb.memory = 2048
    # number of Physical CPUs to allocate
    vb.cpus = 2
    # allow vagrant to create symlinks
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
end
